FROM --platform=linux/amd64 public.ecr.aws/sam/build-python3.10:latest
# docker build - t requirements_binaries .
# docker run -t -v $(pwd):/mnt requirements_binaries /bin/sh -c "pip install -r /mnt/requirements.txt -t /mnt/li

